from source.theano.utils import load_data

load_mnist_for_test = load_data.load_mnist_for_test
load_mnist_for_validation = load_data.load_mnist_for_validation
load_mnist_for_semi_sup = load_data.load_mnist_for_semi_sup